sudo: false
language: node_js
cache:
  directories:
  - node_modules
git:
  submodules: false
notifications:
  email: false
node_js:
- '4'
before_install:
- touch ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_c65a37809828_key -iv $encrypted_c65a37809828_iv -in .travis/travis_ssh.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm i -g npm@^2.0.0
- npm i -g hexo-cli
before_script:
- npm prune
- git config --global user.name 'Travis CI'
- git config --global user.email 'travis-ci@travis-ci.org'
script:
- npm install
- hexo generate
after_success:
- hexo deploy
branches:
  only:
  - hexo