menu:
  Home: /
  Archives: /archives
  About: /about
  RSS: /atom.xml

widgets: 
- search
- category
- recent_posts
- tag
- tagcloud
- recent_comments

excerpt_link: Read More

twitter:
  username: cslinmiso
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: true

fancybox: true

google_analytics: UA-53783277-1
rss: /atom.xml
